services:
  postgres:
    image: postgres:17
    container_name: procedures-postgres
    environment:
      POSTGRES_DB: procedures
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - procedures_postgres_data:/var/lib/postgresql/data

volumes:
  procedures_postgres_data:
